version: "3"
services:
  code-server:
    build: .
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
      - PASSWORD
    volumes:
      - codeserver:/config
    ports:
      - 8443:8443
    restart: unless-stopped
volumes:
  codeserver: